// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCurrencySymbolParams creates a new GetCurrencySymbolParams object
// no default values defined in spec.
func NewGetCurrencySymbolParams() GetCurrencySymbolParams {

	return GetCurrencySymbolParams{}
}

// GetCurrencySymbolParams contains all the bound params for the get currency symbol operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetCurrencySymbol
type GetCurrencySymbolParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Symbol string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCurrencySymbolParams() beforehand.
func (o *GetCurrencySymbolParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSymbol, rhkSymbol, _ := route.Params.GetOK("symbol")
	if err := o.bindSymbol(rSymbol, rhkSymbol, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSymbol binds and validates parameter Symbol from path.
func (o *GetCurrencySymbolParams) bindSymbol(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Symbol = raw

	return nil
}
