// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCurrencySymbolHandlerFunc turns a function with the right signature into a get currency symbol handler
type GetCurrencySymbolHandlerFunc func(GetCurrencySymbolParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCurrencySymbolHandlerFunc) Handle(params GetCurrencySymbolParams) middleware.Responder {
	return fn(params)
}

// GetCurrencySymbolHandler interface for that can handle valid get currency symbol params
type GetCurrencySymbolHandler interface {
	Handle(GetCurrencySymbolParams) middleware.Responder
}

// NewGetCurrencySymbol creates a new http.Handler for the get currency symbol operation
func NewGetCurrencySymbol(ctx *middleware.Context, handler GetCurrencySymbolHandler) *GetCurrencySymbol {
	return &GetCurrencySymbol{Context: ctx, Handler: handler}
}

/*GetCurrencySymbol swagger:route GET /currency/{symbol} getCurrencySymbol

Retrieve information about a single currency

*/
type GetCurrencySymbol struct {
	Context *middleware.Context
	Handler GetCurrencySymbolHandler
}

func (o *GetCurrencySymbol) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCurrencySymbolParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
