// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/scottshotgg/toyota-test/models"
)

// GetCurrencyAllOKCode is the HTTP code returned for type GetCurrencyAllOK
const GetCurrencyAllOKCode int = 200

/*GetCurrencyAllOK success m8

swagger:response getCurrencyAllOK
*/
type GetCurrencyAllOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Currency `json:"body,omitempty"`
}

// NewGetCurrencyAllOK creates GetCurrencyAllOK with default headers values
func NewGetCurrencyAllOK() *GetCurrencyAllOK {

	return &GetCurrencyAllOK{}
}

// WithPayload adds the payload to the get currency all o k response
func (o *GetCurrencyAllOK) WithPayload(payload []*models.Currency) *GetCurrencyAllOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get currency all o k response
func (o *GetCurrencyAllOK) SetPayload(payload []*models.Currency) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrencyAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Currency, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
