// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Toyota Test",
    "title": "Toyota Test",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "localhost",
  "paths": {
    "/currency/all": {
      "get": {
        "summary": "Retrieve information for every currency",
        "responses": {
          "200": {
            "description": "success m8",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/currency"
              }
            }
          }
        }
      }
    },
    "/currency/{symbol}": {
      "get": {
        "summary": "Retrieve information about a single currency",
        "parameters": [
          {
            "type": "string",
            "name": "symbol",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success m8",
            "schema": {
              "$ref": "#/definitions/currency"
            }
          },
          "404": {
            "description": "success m8"
          }
        }
      }
    }
  },
  "definitions": {
    "currency": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Toyota Test",
    "title": "Toyota Test",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "localhost",
  "paths": {
    "/currency/all": {
      "get": {
        "summary": "Retrieve information for every currency",
        "responses": {
          "200": {
            "description": "success m8",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/currency"
              }
            }
          }
        }
      }
    },
    "/currency/{symbol}": {
      "get": {
        "summary": "Retrieve information about a single currency",
        "parameters": [
          {
            "type": "string",
            "name": "symbol",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success m8",
            "schema": {
              "$ref": "#/definitions/currency"
            }
          },
          "404": {
            "description": "success m8"
          }
        }
      }
    }
  },
  "definitions": {
    "currency": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      }
    }
  }
}`))
}
