// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Currencies currencies
// swagger:model currencies
type Currencies struct {

	// currencies
	Currencies []*Currency `json:"currencies"`
}

// Validate validates this currencies
func (m *Currencies) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrencies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Currencies) validateCurrencies(formats strfmt.Registry) error {

	if swag.IsZero(m.Currencies) { // not required
		return nil
	}

	for i := 0; i < len(m.Currencies); i++ {
		if swag.IsZero(m.Currencies[i]) { // not required
			continue
		}

		if m.Currencies[i] != nil {
			if err := m.Currencies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("currencies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Currencies) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Currencies) UnmarshalBinary(b []byte) error {
	var res Currencies
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
