// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Currency currency
// swagger:model currency
type Currency struct {

	// ask
	Ask string `json:"ask,omitempty"`

	// bid
	Bid string `json:"bid,omitempty"`

	// fee currency
	FeeCurrency string `json:"feeCurrency,omitempty"`

	// full name
	FullName string `json:"fullName,omitempty"`

	// high
	High string `json:"high,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// last
	Last string `json:"last,omitempty"`

	// low
	Low string `json:"low,omitempty"`

	// open
	Open string `json:"open,omitempty"`
}

// Validate validates this currency
func (m *Currency) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Currency) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Currency) UnmarshalBinary(b []byte) error {
	var res Currency
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
